export const MUSIC_NFT_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_MUSIC_NFT_CONTRACT_ADDRESS || "";
export const ALBUM_NFT_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_ALBUM_NFT_CONTRACT_ADDRESS || "";
export const BADGE_NFT_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_BADGE_NFT_CONTRACT_ADDRESS || "";
export const MERCHANDISE_NFT_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_MERCHANDISE_NFT_CONTRACT_ADDRESS || "";
export const EVENT_TICKET_NFT_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_EVENT_TICKET_NFT_CONTRACT_ADDRESS || "";
